services:
  node:
    build: 
      context: ./node
    container_name: app
    entrypoint: ["sh", "-c", "dockerize -wait tcp://db:3306 -timeout 30s && npm install && node index.js"]
    networks:
      - node-network
    volumes:
      - ./node:/home/node/app
    tty: true
    depends_on:
      - db

  db:
    image: mysql:9.0.1
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=desafiodb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build: 
      context: ./nginx
    container_name: reverse_proxy
    networks:
      - node-network
    ports:
      - "8080:8080"
    depends_on:
      - node

networks:
  node-network:
    driver: bridge